### ISSUE TITLE
AI stuck with Reversed Accounts

### ISSUE THREAD

**Issue by Shokyuu** [bobtheuberfish/chiriboga#101]
Just finished a very weird game where the AI placed a Reversed Accounts asset in turn 1 and kept putting ice in front of it the whole game, only advancing it twice and never using its ability.

Also it put Palisade on HQ in turn 1 and put Regolith Mining License out in the open in the middle of the game at the end of its turn. Not sure about these decisions either.

[chiriboga-log-2022-10-02T03_16_39.031Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9691760/chiriboga-log-2022-10-02T03_16_39.031Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report. I will investigate this.
The Palisade play can be ok if the Corp has agendas in hand and no better ice options.
Installing Regolith without protection is probably fine - it costs 3 credits to trash. It might not be the best move but I think it's not terrible.

**Comment by Shokyuu** [comment]
Well, the AI had this hand: [Palisade,Reversed Accounts,Tollbooth,Pop-up Window,Predictive Planogram] and put out the asset and 3 ices, one of those the Palisade on HQ.
Regarding the Regolith, it put it out at the end of its turn as a last click, I had 2 credits also so it was almost already in danger (putting it out like that with 0 credit might make some sense).

**Comment by bobtheuberfish** [comment]
That extra analysis is helpful. I think both of those are worth looking into, but they're minor enough not to be high priority. I'll aim to eventually look into all three of these things. Thanks again.

**Comment by bobtheuberfish** [comment]
This should be fixed as of the Subliminal Messaging update.
