### ISSUE TITLE
As runner, having my grip emptied did not cause me to lose

### ISSUE THREAD

**Issue by PashMK** [bobtheuberfish/chiriboga#102]
Title. If it helps, I took damage equal to my hand size, i.e. 2, from accessing Urtica Cipher in a remote with no advancements.

See screenshot where it is the start of my turn and I have no cards in my hand:

![image](https://user-images.githubusercontent.com/75437421/196217320-c59da84b-5bb2-4397-b161-11006de368d2.png)

**Comment by bobtheuberfish** [comment]
Thank you for this report and especially for the screenshot.
I am glad to hear you were not flatlined - that only happens when you receive _more_ damage than cards in hand.
Now that you have zero cards in hand, if you were to take another damage, you would lose. But zero cards you can keep playing!

**Comment by PashMK** [comment]
I see! Then please disregard!
