### ISSUE TITLE
I cannot rez Malapert Data Vault

### ISSUE THREAD

**Issue by olompumpa** [bobtheuberfish/chiriboga#110]
I couldn't rezzzz Malapert Data Vault (this upgrade was seen by the Runner earlier).

Thanks so much for your work, this site is incredible!
[chiriboga-log-2022-12-26T18 21 41.963Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10304493/chiriboga-log-2022-12-26T18.21.41.963Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report and log. I will take a look.
I noticed you are using the 'stable' version which doesn't have all the latest updates (but also doesn't have all the new bugs). If you would like to be testing the latest version, use https://chiriboga.sifnt.net.au/su2021/
If you'd like to deckbuild but want to limit the card pool to only System Gateway, use these links:
https://chiriboga.sifnt.net.au/su2021/decklauncher.php?sets=systemgateway&p=r&r=random
https://chiriboga.sifnt.net.au/su2021/decklauncher.php?sets=systemgateway&p=c&c=random

**Comment by olompumpa** [comment]
I have shared the page with my friends. It is simply brilliant. We have been waiting for a single-player mode (to test decks and teach new people) for a very long time.

How can we support you in your work?
Do you have a patreon page? Is there any way I can support you?
For sure, if you are in Szeged (Hungary), you are my guest for a beer. :)

Question:
Is there a possibility to play Chiriboga offline?
Thanks in advance for the answers!

**Comment by olompumpa** [comment]
I found your solution for running offline.
Perfect.
Thx! :)
https://github.com/bobtheuberfish/chiriboga/wiki/Running-locally

PS:
-minor-bug-report-
1)
Running with Overclock against Whitespace-ICE:
subr.- The Runner loses 3 credits
I cannot pay it from Overclock.
(su2021)


2)
Docklands Pass doesnt work. (no additional access) 
[chiriboga-log-2022-12-28T14 46 56.933Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10314780/chiriboga-log-2022-12-28T14.46.56.933Z.txt)

[chiriboga-log-2022-12-28T17 46 32.922Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10315585/chiriboga-log-2022-12-28T17.46.32.922Z.txt)

**Comment by bobtheuberfish** [comment]
Hi,

Thanks for your kind words!

I am in Australia but it's ok I have plenty of beer.

If I understand the bug you have described with Overclock, it is not a bug.
According to NSG's rules, you can only 'lose' credits from your pool.

Tom

**Comment by kilianmc** [comment]
hello, i think this is a general issue with upgrades. i think you coded that they can only be rezzed before the access to that server, but if i am not mistaken, when an asset or upgrade is installed, the Corporation can pay its rez cost to rez it at almost any time. like spin doctor for example.

**Comment by bobtheuberfish** [comment]
Thank you for your comment. That's true, they should be rezzable any time, but I found that it was tedious to press "Continue" every opportunity to rez. I haven't yet decided on a solution to this issue.

**Comment by kilianmc** [comment]
First thanks for this great game, is awesome that you pulled this. I was thinking that you choose that solution intentionally the moment i saw how leaving "spin doctor" on the table makes you want to kill yourself clicking continue every time... now i know for sure :). If i can suggest i would use same technique as some other games uses (flag for stops), so when you have anything that leaves you choice to use it anytime, you can prompt the usr with a button that lets them decide. Do you want the game to ask you to use it anytime you could?, or you want to retain the normal game stops windows?, and then its on them. (also if there was a way to bind a "key" to continue would make this interactions so much quicker...)

**Comment by bobtheuberfish** [comment]
You should now be able to rez Malapert properly. I've also added an 'auto skip' button can now be used to skip through tedious prompts (it will automatically appear when relevant). You can also press the Enter key to continue.
