### ISSUE TITLE
2nd console-install / HQ access

### ISSUE THREAD

**Issue by olompumpa** [bobtheuberfish/chiriboga#111]
1.) 
I cannot install a 2nd console. I believe you really couldn't under the old rule, but that's been changed:
https://nullsignal.games/blog/quick-notes-comprehensive-rules-1-5/
"Consoles now work just like unique cards: there’s no restriction on installing them, but if more than one is ever installed at the same time, all but the most recent one are trashed at the next checkpoint."

2.)
As a Runner, when I run to HQ for the second or third time, etc (in the same turn, with no multiple access), I always access the same card. There is no randomization of access within a turn. 

[chiriboga-log-2023-01-08T19 04 50.364Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10369360/chiriboga-log-2023-01-08T19.04.50.364Z.txt)

Thank You in advance!

**Comment by bobtheuberfish** [comment]
Thank you, I will investigate these.
