### ISSUE TITLE
Not able to click on Botulus

### ISSUE THREAD

**Issue by plotinusreadinggroup** [bobtheuberfish/chiriboga#113]
I was not able to click on the Botulus on the Tithe on HQ in this game while in fullscreen mode, as instead I could only click on the Botulus below. I was  able to interact with it once I exited fullscreen mode though. Using FIrefox Browser 108.0.2. 

[chiriboga-log-2023-01-10T05 32 11.690Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10379288/chiriboga-log-2023-01-10T05.32.11.690Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report and for including the log. I will look into this.

**Comment by olompumpa** [comment]
As a Runner, when I play the Test Run (for Botulus), I don't have the option to choose a hosting ICE for Botulus.

After TestRun, Botulus does not lose the virus counter and returns to the top of the deck with it.

Thank you
Best regards
OP
[chiriboga-log-2023-01-14T10 19 49.383Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10417123/chiriboga-log-2023-01-14T10.19.49.383Z.txt)

**Comment by bobtheuberfish** [comment]
Fixed Botulus gaining virus counters in stack after Test Run
Fixed not able to choose ice target for Test Run Botulus
Was not able to replicate "Not able to click on Botulus"
