### ISSUE TITLE
Different card availability on mobile vs. desktop

### ISSUE THREAD

**Issue by rdef** [bobtheuberfish/chiriboga#118]
I've been playing on my phone and on my laptop. Accessing the site on my phone has access to the System Update 2021 cards, while the laptop does not. This includes identities and base cards. This may or may not be intentional.

Also, just to add, this has been a really fun implementation for me to play away from social settings, and am really enjoying it.

**Comment by bobtheuberfish** [comment]
Are you using the same web address on both devices? Can you please send me a screenshot of what the mobile site looks like for you?

Thanks!
