### ISSUE TITLE
Runner will unsafely re-run Urtica Cipher if an upgrade is installed in the same server later

### ISSUE THREAD

**Issue by samb91** [bobtheuberfish/chiriboga#122]
1. Install an Urtica Cipher in a new remote server, unprotected (for best result double advance it)
2. The runner will run it safely (i.e. by drawing up enough cards to survive first)
3. On a later turn, install an upgrade in the Urtica Cipher server without trashing UC
4. At some later point, dependent on its priorities, the runner may run the server again unsafely (i.e. with fewer than 4 cards in hand)
5. This can be repeated multiple times with further upgrades, provided the runner doesn't flatline itself first

The runner does not appear to 'remember' that the asset it accessed was Urtica Cipher and/or doesn't treat known advanced assets as potentially dangerous (unlike unknown advanced assets, where it draws up first). This enables some cheesy wins, which is admittedly quite fun.

[A log for a game demonstrating this](https://github.com/bobtheuberfish/chiriboga/files/10925312/chiriboga-log-2023-03-08T21.08.37.971Z.txt).

**Comment by bobtheuberfish** [comment]
Thank you for this report and especially for including the log and instructions to make it happen. I will investigate this.

**Comment by bobtheuberfish** [comment]
This has now been fixed on the development version, https://chiriboga.sifnt.net.au/su2021/
If there are no new bugs in the next 7 days the main site will be updated with this new version, https://chiriboga.sifnt.net.au/
