### ISSUE TITLE
Ability to toggle between Core and System Update sets

### ISSUE THREAD

**Issue by mikeriley** [bobtheuberfish/chiriboga#123]
Great work on this project, especially when trying out different NR strategies.

Since the effort has already been made to implement the original Core Set specifications (found in sets->coreset.js), is there any way to easily add a toggle to allow users/visitors to switch between that original set and the newer System Update set? 

It would also be great if an import function existed to quickly import other sets and add them to the start game options to allow players to select Corp/Runner decks from multiple sets.

Thanks for your consideration.

**Comment by bobtheuberfish** [comment]
Thank you for the feedback.
Unfortunately the core set file is vestigial and would currently not even run. I would like to eventually finish it and add tools to choose which sets are available, but I cannot make any promises at this stage. I would also love to be able to allow users to swap in custom card art but I haven't figured out how to do it.
For now I will mark this as wontfix but maybe one day down the track I'll figure out how to do it (or someone else might!)

**Comment by mikeriley** [comment]
Understood - thank you for your consideration, and keep up the excellent work on the project!

**Comment by bobtheuberfish** [comment]
I thought you would like to know that I am joining another in-progress Netrunner project. I will still maintain Chiriboga in terms of handling issues and fixing bugs but I don't intend to add new cards. This other project does not have AI yet but it has many many cards implemented and the lead developer is someone with professional experience so it has better long-term potential. If you are interested in being involved I'm sure your contributions would be appreciated, just let me know.

**Comment by GuidoOffermans** [comment]
Hey great work on this project! I just got into netrunner again after years and this was a great tool to learn :)

In the last comment you have mentioned that you started working on another project that could use some help. I'm a web dev by trait and would to give a hand. Where could I find this project or how could I contribute?

Thanks!

**Comment by bobtheuberfish** [comment]
Find me via Discord on Green Level Clearance.

**Comment by bobtheuberfish** [comment]
Since we're making good progress in our new project I am closing this issue. I have created a new issue specifically about the new project for anyone else who is interested.
