### ISSUE TITLE
Project Vitruvius error

### ISSUE THREAD

**Issue by olompumpa** [bobtheuberfish/chiriboga#124]
I couldn't put back cards to my hand with Project Vitruvius
It had two agenda counters
(it worked in later rounds)

Thanks for the help!
[chiriboga-log-2023-03-15T07 40 48.481Z.txt](https://github.com/bobtheuberfish/chiriboga/files/10977199/chiriboga-log-2023-03-15T07.40.48.481Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report. I will investigate this.
