### ISSUE TITLE
Missing Image Assets

### ISSUE THREAD

**Issue by mikeriley** [bobtheuberfish/chiriboga#125]
A number of image assets appear to be missing in the /images folder. For example, on the home page (index.php), these png's are not included in the repo:

/images/chiriboga_icon.png
/images/menu_runner_3_sg.png
/images/menu_runner_4_sg_su21.png
/images/menu_corp_3_sg.png
/images/menu_corp_4_sg_su21.png

And all the images referenced in the decklauncher.php (do the System Gateway and System Update 2021 card images need to be individually downloaded from netrunnerdb?) and engine.php (cards, card backs, icons, counters, etc.) are missing as well. This results in the playfield Loading screen staying stuck at 0%.

**Comment by bobtheuberfish** [comment]
I assume you are running the game locally or hosting the game yourself?

It sounds like you don't have the latest version of the images folder. Please redownload the images from step 3 of these instructions: https://github.com/bobtheuberfish/chiriboga/wiki/Running-locally

**Comment by mikeriley** [comment]
Yup, that was it - my apologies for not reading the Wiki. BTW - I have created a Dockerfile and docker-compose.yml file for containing the app to make it easier to deploy and run on various development platforms. I can submit a pull request if you're interested.

**Comment by bobtheuberfish** [comment]
Thanks, feel free! I don't know much about web development but since the app is PHP and HTML doesn't it just run without any kind of deployment process?
Please keep in mind that we can't package any of the NSG assets here because I want to be clear they are property of NSG.
