### ISSUE TITLE
Funhouse has lost the option to end the run when encountered 

### ISSUE THREAD

**Issue by steveYeah** [bobtheuberfish/chiriboga#126]
Noticed this happened consistently in the past couple of games played. Instead of giving the option to end the run, the tag was applied and I was forced to encounter

Many thanks! :)

**Comment by bobtheuberfish** [comment]
Should be fixed now. Thanks for reporting it!

**Comment by steveYeah** [comment]
Awesome! Thanks for your hard work! I got into the game via Chiriboga :)
