### ISSUE TITLE
Whitespace ICE uses credits before Overclock credits

### ISSUE THREAD

**Issue by alexzhaohong** [bobtheuberfish/chiriboga#132]
Issue: [Whitespace][ws] ICE uses credits before [Overclock][oc] credits

Scenario: As runner, I played [Overclock][oc] and ran a server with zero icebreakers and 7 credits + (5 hosted credits). I encountered a [Whitespace][ws] which auto-fired, reducing me to 4 credits + (5 hosted credits). On the second subroutine _If the Runner has 6c or less, end the _run.,__ the run ended.

Expected Outcome: The first subroutine, _The Runner loses 3c_, should have reduced me to  7 credits + (1 hosted credits), allowing the run to continue.

Impact: Low. This is a 2-card interaction bug and not something higher priority, such as implementation or new feature development. Both cards are System Gateway cards and I do not think this bug has been reported before. I believe replicating this bug requires someone to face-check into a Whitespace with zero icebreakers.

Log: [chiriboga-log-2023-04-04T07_16_42.818Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11145679/chiriboga-log-2023-04-04T07_16_42.818Z.txt)

[ws]:https://netrunnerdb.com/en/card/30074
[oc]:https://netrunnerdb.com/en/card/30029

**Comment by bobtheuberfish** [comment]
Thank you for this report and for including the log.
This is correct behaviour as per FAQ here: https://netrunnerdb.com/en/card/30074
`“Losing” credits always drains the Runner’s credit pool.`

**Comment by alexzhaohong** [comment]
Thanks! I should have read the Whitespace and Overclock rulings!
