### ISSUE TITLE
Effects from successful run using Sneakdoor Beta not firing

### ISSUE THREAD

**Issue by genbod** [bobtheuberfish/chiriboga#138]
I used sneakdoor beta and had a successful run on HQ but didn't get the effect from Steve Cambridge.  I also played Mutual Favor and got Femme Fatale but it was added to my grip instead of getting installed.
[chiriboga-log-2023-05-21T13_05_38.612Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11524614/chiriboga-log-2023-05-21T13_05_38.612Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report. I will investigate it.

**Comment by bobtheuberfish** [comment]
I tested the described behaviours today and they worked correctly for me. My theory for why they didn't work for you:

- Steve Cambridge requires at least two cards in Heap (from your log it seems you had 0 cards in Heap)
- Mutual Favor requires you to pay the install cost (from your log it seems you had 0 credits left)

**Comment by genbod** [comment]
Oh right.  I got confused between Heap and Stack and thought Mutual Favor didn't make you pay the cost.  My mistake.
