### ISSUE TITLE
Access order at a remote server

### ISSUE THREAD

**Issue by olompumpa** [bobtheuberfish/chiriboga#140]
I broke a remote server which had 3 cards, but I could not select the order of accesses.

Thanks in advance for the fix
[chiriboga-log-2023-05-31T09 00 59.205Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11614813/chiriboga-log-2023-05-31T09.00.59.205Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report and for the log. I will look into this.

**Comment by bobtheuberfish** [comment]
I have not been able to recreate this error. From your log it looks like the server was Project Vitruvius, SanSan City Grid, and Manegarm Skunkworks. I recreated this scenario and when I breached I was able to access the cards in order of my choice.

**Comment by bobtheuberfish** [comment]
Have you seen this error again at all? If not I can close this issue.

**Comment by olompumpa** [comment]
Not yet.
But if I do encounter this error again then I will write it.
You can close this issue. thx
