### ISSUE TITLE
Tutorials not starting

### ISSUE THREAD

**Issue by Saurbaum** [bobtheuberfish/chiriboga#143]
Attempting to start the runner tutorial, it finished loading and then stops at this screen.

<img width="534" alt="image" src="https://github.com/bobtheuberfish/chiriboga/assets/7288848/3f07fa7c-2189-4376-a7e3-edb72e97782b">

**Comment by bobtheuberfish** [comment]
Thank you for reporting this. It is working fine for me, hopefully with more information I can replicate it.
What browser are you using? What operating system?
Any chance you can Download the captured log and attach it here? (click the hat icon).
Or even better open the Developer Console, refresh the page and take a screenshot of the messages?

**Comment by Saurbaum** [comment]
Windows 11 and Edge

One log file attached

[chiriboga-log-2023-06-08T19_36_09.467Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11692289/chiriboga-log-2023-06-08T19_36_09.467Z.txt)

**Comment by Saurbaum** [comment]
Console log

utility.js?1680247056:49 Game begins
utility.js?1680247056:49 
    PixiJS 4.7.0 - ✰ Canvas ✰      http://www.pixijs.com/    ♥♥♥ 
TextMetrics.js:220  Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
t.measureFont @ TextMetrics.js:220
t.measureText @ TextMetrics.js:287
e.updateText @ Text.js:133
e._renderCanvas @ Text.js:381
e.renderCanvas @ Container.js:479
e.renderCanvas @ Container.js:500
e.render @ CanvasRenderer.js:235
t.render @ Application.js:78
t.emit @ TickerListener.js:54
t.update @ Ticker.js:379
_tick @ Ticker.js:42
requestAnimationFrame (async)
_tick @ Ticker.js:113
requestAnimationFrame (async)
t._requestIfNeeded @ Ticker.js:135
t.start @ Ticker.js:291
t.start @ Application.js:99
t @ Application.js:75
Renderer @ cardrenderer.js?1674716464:1350
Init @ init.js?1677144035:172
onload @ engine.php?ap=6&p=r&r=N4IglgJgpgdgLmOBPEAuEB2AbCANCAZyQLigFsBxAQ1IHcqVUBtLXVgRgCZcueBmHgBYeAVlE8AHLk4AGaXM7tpSzq1XSMG6VM46dATmmG+ck7jN9ul8wL63BAXQC+QA&c=N4IglgJgpgdgLmOBPEAuEB2DIA0IDOS+cUAtgOICGJA7pSqgNoDMGOr7AnFzgCwAMfQbwBMfAKwS+ANhl82vNtN45lqpRtXdp3DIL04MARkMmMY84YvNDNjCvuHJGZ+IC6AXyA:23
manifest.json:1  Manifest: property 'scope' ignored. Start url should be within scope of scope URL.
utility.js?1680247056:49 (17) ['The Catalyst', '2 Cleaver', '2 Tread Lightly', '1 Docklands Pass', '1 Pennyshaver', '2 Carmen', '1 Red Team', '2 Creative Commission', '2 VRcation', '2 Unity', '2 Telework Contract', '3 Jailbreak', '2 Overclock', '3 Sure Gamble', '2 Mayfly', '2 Smartware Distributor', '1 Verbal Plasticity']
utility.js?1680247056:49 (17) ['The Syndicate', '2 Nico Campaign', '2 Brân 1.0', '2 Seamless Launch', '1 Manegarm Skunkworks', '2 Urtica Cipher', '2 Diviner', '2 Karunā', '2 Government Subsidy', '3 Offworld Office', '2 Send a Message', '2 Superconducting Hub', '2 Regolith Mining License', '3 Palisade', '2 Tithe', '2 Whitespace', '3 Hedge Fund']
utility.js?1680247056:49 Decks shuffled
init.js?1677144035:317  Uncaught TypeError: Cannot set properties of undefined (setting 'length')
    at Render (init.js?1677144035:317:59)
    at Setup (init.js?1677144035:1339:3)
    at t.value (url.js:561:1)
    at t._onComplete (Resource.js:456:1)
    at Resource.js:514:1
    at s (url.js:80:1)
    at e.<anonymous> (interactiveTarget.js:82:5)
    at Resource.js:483:1
    at url.js:85:1
Render @ init.js?1677144035:317
Setup @ init.js?1677144035:1339
value @ url.js:561
t._onComplete @ Resource.js:456
(anonymous) @ Resource.js:514
s @ url.js:80
(anonymous) @ interactiveTarget.js:82
(anonymous) @ Resource.js:483
(anonymous) @ url.js:85
setTimeout (async)
s @ url.js:80
(anonymous) @ loader.js:99
(anonymous) @ Resource.js:483
(anonymous) @ url.js:85
setTimeout (async)
s @ url.js:80
(anonymous) @ spritesheetParser.js:47
(anonymous) @ Resource.js:483
(anonymous) @ url.js:85
setTimeout (async)
s @ url.js:80
(anonymous) @ url.js:415
(anonymous) @ Resource.js:483
(anonymous) @ url.js:85
setTimeout (async)
s @ url.js:80
i @ url.js:90
t._onLoad @ Resource.js:467
value @ url.js:561
t.complete @ Resource.js:813
load (async)
t._loadElement @ Resource.js:925
t.load @ Resource.js:833
(anonymous) @ Resource.js:445
s @ url.js:80
i @ url.js:90
t._loadResource @ Resource.js:436
_boundLoadResource @ Resource.js:89
process @ url.js:231
resume @ url.js:254
t.load @ Resource.js:367
Init @ init.js?1677144035:181
onload @ engine.php?ap=6&p=r&r=N4IglgJgpgdgLmOBPEAuEB2AbCANCAZyQLigFsBxAQ1IHcqVUBtLXVgRgCZcueBmHgBYeAVlE8AHLk4AGaXM7tpSzq1XSMG6VM46dATmmG+ck7jN9ul8wL63BAXQC+QA&c=N4IglgJgpgdgLmOBPEAuEB2DIA0IDOS+cUAtgOICGJA7pSqgNoDMGOr7AnFzgCwAMfQbwBMfAKwS+ANhl82vNtN45lqpRtXdp3DIL04MARkMmMY84YvNDNjCvuHJGZ+IC6AXyA:23
utility.js?1680247056:49 Each player has taken five credits and drawn five cards
init.js?1677144035:317  Uncaught TypeError: Cannot set properties of undefined (setting 'length')
    at Render (init.js?1677144035:317:59)
    at init.js?1677144035:1362:2
    at TriggeredResponsePhase (utility.js?1680247056:2541:47)
    at StartGame (init.js?1677144035:1352:2)
    at Renderer.<anonymous> (cardrenderer.js?1674716464:1520:17)
    at t.emit (TickerListener.js:54:9)
    at t.update (Ticker.js:379:32)
    at _tick (Ticker.js:42:9)
Render @ init.js?1677144035:317
(anonymous) @ init.js?1677144035:1362
TriggeredResponsePhase @ utility.js?1680247056:2541
StartGame @ init.js?1677144035:1352
(anonymous) @ cardrenderer.js?1674716464:1520
t.emit @ TickerListener.js:54
t.update @ Ticker.js:379
_tick @ Ticker.js:42
requestAnimationFrame (async)
_tick @ Ticker.js:113
requestAnimationFrame (async)
_tick @ Ticker.js:113
requestAnimationFrame (async)
_tick @ Ticker.js:113
requestAnimationFrame (async)
t._requestIfNeeded @ Ticker.js:135
t.start @ Ticker.js:291
t.start @ Application.js:99
t @ Application.js:75
Renderer @ cardrenderer.js?1674716464:1350
Init @ init.js?1677144035:172
onload @ engine.php?ap=6&p=r&r=N4IglgJgpgdgLmOBPEAuEB2AbCANCAZyQLigFsBxAQ1IHcqVUBtLXVgRgCZcueBmHgBYeAVlE8AHLk4AGaXM7tpSzq1XSMG6VM46dATmmG+ck7jN9ul8wL63BAXQC+QA&c=N4IglgJgpgdgLmOBPEAuEB2DIA0IDOS+cUAtgOICGJA7pSqgNoDMGOr7AnFzgCwAMfQbwBMfAKwS+ANhl82vNtN45lqpRtXdp3DIL04MARkMmMY84YvNDNjCvuHJGZ+IC6AXyA:23

**Comment by Saurbaum** [comment]
<img width="930" alt="image" src="https://github.com/bobtheuberfish/chiriboga/assets/7288848/40e13db4-0b91-4627-b84e-ca96689bebaf">

**Comment by Saurbaum** [comment]
<img width="749" alt="image" src="https://github.com/bobtheuberfish/chiriboga/assets/7288848/6b637882-ae43-4142-a256-40ab38a05b4f">

**Comment by Saurbaum** [comment]
Well after 24 hours and a reboot it all seems to be working now.
