### ISSUE TITLE
Test run keeps firing

### ISSUE THREAD

**Issue by culoman** [bobtheuberfish/chiriboga#144]
I used Test Run to install Femme Fatale, but I realized I had no MUs left, so I decided not to install it and lose my click and credits. No worries.  
  
But after that, Femme Fatale kept going on top of my deck at the end of any of my turns. It didn't matter whether it was in my hand or in my heap. Turn after turn, the first card I drew was always Femme Fatale.  
  
[chiriboga-log-2023-06-08T08_05_38.896Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11685564/chiriboga-log-2023-06-08T08_05_38.896Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for reporting this. I will look into it.

**Comment by bobtheuberfish** [comment]
This has now been fixed in the development version. Please feel free to access this here and report any bugs:
https://chiriboga.sifnt.net.au/dev
