### ISSUE TITLE
Rezzing assets before trashing 

### ISSUE THREAD

**Issue by morvael** [bobtheuberfish/chiriboga#147]
I've noticed AI likes to rez "Campaign" assets as they are accessed, just before the runner is given option to trash them. It's a loss of credits for the AI, if the runner does so.

**Comment by morvael** [comment]
AI should differentiate between trap assets/upgrades which have to be rezzed, and those that don't.

**Comment by bobtheuberfish** [comment]
I agree the AI should differentiate, and so this should only happen with Marilyn Campaign, so that it goes to R&D instead of Archives. If you see this happen for other campaigns please post a log file here so I can diagnose the problem.

**Comment by morvael** [comment]
Yes, it was Marylin. I assumed it does so with others. He did that with Spin Doctor, but actually it was clever behavior for that card.

**Comment by morvael** [comment]
Marylin doesn't go to R&D if trashed while unrezzed? I might be playing the real game wrong 😀

**Comment by bobtheuberfish** [comment]
The card text is only active while the card is rezzed, as per Ruling on NRBD here: https://netrunnerdb.com/en/card/31042

**Comment by morvael** [comment]
Thanks. Not a bug then, though of course those 2 credits might have better use in a given situation.
