### ISSUE TITLE
AI failed to steal all agendas from Archives

### ISSUE THREAD

**Issue by Prinny-Wizz** [bobtheuberfish/chiriboga#148]
Hi,

I just ran into an odd bug. The short version is that I was playing Personal Evolution, intentionally dumped three 1-point agendas into Archives, and when the runner hit Archives they only stole two of them. (The log should be attached.)

At first I thought maybe I had misremembered, and didn't check Archives manually, so I finished the game; it wasn't until the runner hit Archives again and stole the third agenda (which flatlined them) I realised I *hadn't* misremembered. I'm not sure why it couldn't steal all three the first time?
(I don't imagine this comes up often, for what it's worth. It's only a relevant tactic with PE and it's also quite risky.)

And now I've covered the pertinent bits - I want to say thank you for providing this tool, it's a great way to kill time  and/or try new tactics, on mobile especially :D 

[chiriboga-log-2023-08-19T22_43_52.278Z.txt](https://github.com/bobtheuberfish/chiriboga/files/12386827/chiriboga-log-2023-08-19T22_43_52.278Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report. I can see what you described happening in the log but I can't think of how the Runner could avoid accessing all the cards. I will investigate this.
