### ISSUE TITLE
Rewinding Does Not Remove Tag

### ISSUE THREAD

**Issue by SummitPatel** [bobtheuberfish/chiriboga#149]
Hi,

I was playing as the Runner and I rewinded time to see how the Corp would react if I chose to take a tag. After rewinding, the tag is still persistent. I would expect that if I rewinded time to before taking the tag that it should not be there.

 I've attached the logs for reference.

[chiriboga-log-2023-09-06T15 30 08.548Z.txt](https://github.com/bobtheuberfish/chiriboga/files/12539693/chiriboga-log-2023-09-06T15.30.08.548Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report and for attaching the log. I will look into this.

**Comment by bobtheuberfish** [comment]
Should be fixed :)
