### ISSUE TITLE
Rototurret automatically firing on mimic

### ISSUE THREAD

**Issue by Luxidream** [bobtheuberfish/chiriboga#157]
[chiriboga-log-2024-03-08T14_24_52.621Z.txt](https://github.com/bobtheuberfish/chiriboga/files/14539285/chiriboga-log-2024-03-08T14_24_52.621Z.txt)

I used red team to run HQ and tried to break rototurret with mimic, but wasn't given the chance to interface.

**Comment by bobtheuberfish** [comment]
Thank you for reporting this bug. I will investigate it.

**Comment by bobtheuberfish** [comment]
Thank you especially for including your log. It turns out you had no credits left in your pool each time you encountered the Rototurret. Mimic has a 1 credit cost to use the ability.
