### ISSUE TITLE
Just a small token of appreciation

### ISSUE THREAD

**Issue by NyarlathotepZERO** [bobtheuberfish/chiriboga#158]
I just wanted to extend my immense gratitute for the time and effort you have spent in bringing your AI Netrunner project to fruition. I have wished for something like this for more years than I care to count.

I'm without doubt that to date, you have provided the BEST solo platform for interacting with and getting to know the gateway cards a little better. It fills in perfectly; the gap where that missing stepping stone always was, revealing a more solid path to R/L opponents/Jinteki etc.

You have done a great service to the game and it's future community.

o7

**Comment by bobtheuberfish** [comment]
Thank you so much for your kind words! It means a lot to me that my work is appreciated.
