### ISSUE TITLE
Mayfly not getting trashed.

### ISSUE THREAD

**Issue by Simberto** [bobtheuberfish/chiriboga#159]
In my attached game, the AI played a Mayfly, used it multiple times, and it didn't ever get trashed at the end of the run.

[chiriboga-log-2024-05-10T17 39 39.406Z.txt](https://github.com/bobtheuberfish/chiriboga/files/15278241/chiriboga-log-2024-05-10T17.39.39.406Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report, especially for attaching the game log.
I have searched through your attached game log and can't find any times when the Runner used Mayfly. The card was installed but never used, which would explain why it didn't get trashed.
I just played a game myself against the Runner AI and when they used Mayfly it was trashed correctly.
If this happens to you again I would be interested to see a screenshot.
Do you recall whether the game actually said that the Runner used Mayfly? Or is it possible that something else was happening? For example, the glowing line between the Mayfly and the ICE doesn't mean that Mayfly is being used. The line just indicates that the Runner _could_ use it.

**Comment by Simberto** [comment]
Ah, that may explain it, I interpreted the glowing line as the runner using Mayfly. Sorry for the confusion!
