### ISSUE TITLE
Issue adding card "The Maker’s Eye"

### ISSUE THREAD

**Issue by NyarlathotepZERO** [bobtheuberfish/chiriboga#160]
I tried pasting "The Maker’s Eye" text into a custom runner deck, though it would not recognize the card from this text, nor would it recognize it if there was a number placed in front of it.

If I began to type the word "the", "The Maker's Eye" card was suggested and was able to be added correctly. It's a strange issue and I'm not sure exactly why it would recognize one and not the other. I hope I have sufficiently explained it.

For the record the deck/text was copied from a NetrunnerDB jinteki.net export and all the other cards in the deck displayed correctly, not sure if this would change anything.

Some screenshots are attached to help explain the issue:

![Screenshot 2024-05-26 110300](https://github.com/bobtheuberfish/chiriboga/assets/26475624/df63a0f5-d887-4277-a4a2-7452b957b40f)
![Screenshot 2024-05-26 110241](https://github.com/bobtheuberfish/chiriboga/assets/26475624/a5a8f232-16f2-45d4-97fa-e1fa80e0d4da)
![Screenshot 2024-05-26 110230](https://github.com/bobtheuberfish/chiriboga/assets/26475624/0cc127c5-7835-4f07-8419-0dc9b1d421d2)

edit: As a further note, if I remove the text from the past char by char, it seems to be having an issue with the apostrophe, and once removed it suggests the correct card as expected.

Some further research and it seems the issue may be the difference in unicode char used between the 2:
U+2019 : RIGHT SINGLE QUOTATION MARK {single comma quotation mark} (NetrunnerDB)
U+0027 : APOSTROPHE {single quote; APL quote} (Chiriboga)

I'll leave this here for you anyway; to fix and/or close as you see fit.

**Comment by bobtheuberfish** [comment]
Thanks for reporting this. Only 12 characters of code to fix!
