### ISSUE TITLE
Orbital Superiority effect doesn't work when stolen by Runner

### ISSUE THREAD

**Issue by DDarkray** [bobtheuberfish/chiriboga#35]
[chiriboga-log-2021-12-21T04_25_15.698Z.txt](https://github.com/bobtheuberfish/chiriboga/files/7749545/chiriboga-log-2021-12-21T04_25_15.698Z.txt)

Orbital Superiority effect doesn't work when stolen by Runner. See attachment.

**Comment by bobtheuberfish** [comment]
Hi, thank you for creating this report and attaching the log. If I understand your description (the log matches this) then that sounds like correct behaviour. Orbital Superiority text says "When you score...". There is no mention of when it is stolen. For contrast see Send a Message which triggers whether it is "scored or stolen".
Is that ok or is there something I've missed?

**Comment by DDarkray** [comment]
Oh dang, you’re right! All this time, my brain thought it works when stolen as well… Please ignore everything I said.
