### ISSUE TITLE
Tāo Salonga: Telepresence Magician does not swap ICE.

### ISSUE THREAD

**Issue by sekoku** [bobtheuberfish/chiriboga#36]
```
"AI: I could advance a card"
"Corp spent one click"
"Corp spent one credit"
"Card advanced"
"Offworld Office scored"
"Corp gained 7 credits"
"\"Pantograph: Gain 1[c], you may install 1 card\" triggered"
"Runner gained one credit"
"Runner spent 3 credits"
"Runner installed Echelon"
"\"Tāo Salonga: Swap 2 installed pieces of ice\" triggered"
"[hidden card] in Remote 0 swapped with [hidden card] in HQ"
```

[This is how it looks.](https://imgur.com/s4DhAC0) AFAIK, Tāo works like Painter and other Shaper replacement/swap effects where it doesn't "turn one card vertical" but physically swaps the two ICE in their positions.

**Comment by sekoku** [comment]
Actually, I think it isn't a bug but the fact that the remote being swapped out "closes" the server and the ICE is flipped and the swapped ICE from the remote goes where the last one was (HQ). I don't think that's "valid" (and would have to check NISEI's ruleset on this) because I think the server would still be physically "alive" because of the swap isn't really "destroying" the server just swapping ICE?

**Comment by bobtheuberfish** [comment]
Thank you for reporting this. I'm having trouble understanding what's happened here. From what you've send it sounds like we agree on what the behaviour should be but I'm confused about what the picture is showing. It looks like there is a bug and you might well be right about the cause - I'll need to try and replicate it somehow!
Are those two facedown cards in front of HQ the cards we're concerned with? It's bizarre that one of them is vertical. Is one of them the ice that was originally in Remote 0? Was the other one in front of HQ or in the corp's hand?

**Comment by sekoku** [comment]
> Are those two facedown cards in front of HQ the cards we're concerned with?

Yes.

>It's bizarre that one of them is vertical. Is one of them the ice that was originally in Remote 0?

The vertical one is the one the AI put at HQ originally. The one that replaced it is the (former) Server 0's ICE. I "switched" them thinking it was going to move the HQ ICE over and the remote's to HQ, but the environment flipped the HQ ice vertical and put the remote there. Which is what threw me off on the interaction.

**Comment by bobtheuberfish** [comment]
Ah yep ok. Thanks.
