### ISSUE TITLE
Diviner ends the run if a card with cost 0 is trashed

### ISSUE THREAD

**Issue by PreNic** [bobtheuberfish/chiriboga#39]
It seems that the subroutine on Diviner considers 0 as a value that ends the run.

**Comment by bobtheuberfish** [comment]
Thank you for this report. I have not yet been able to replicate this bug. For example I played a game just now in which Smartware Distributor was trashed (it has 0 cost) and the run was not ended,
The line in the code is this:
`if (printedCost % 2 == 1) EndTheRun();`
The printed cost variable is not modified at runtime and 0 % 2 is not equal to 1 so I can't see any reason in the code why this happened for you.
If this happens again, please upload the log file and screenshot (you can download the log from the in-game menu).

**Comment by PreNic** [comment]
Hello, thank you for the feedback. The only explanation that I have in mind
is that it could have been that a Mayfly or a similar 1 cost program was
discarded. If I had a DZMZ in play it could be that the displayed cost on
the card was zero even if the printed cost is 1. So I was wrongly assuming
that a zero card had triggered diviner.

Best regards,
Nicola

Il lun 17 gen 2022, 07:15 bobtheuberfish ***@***.***> ha
scritto:
