### ISSUE TITLE
AI makes a run on a server with no unrezzed ice but then quits halfway

### ISSUE THREAD

**Issue by beorik** [bobtheuberfish/chiriboga#40]
Towards the end of the attached game, the AI repeatedly decides to run on an already-rezzed Funhouse, but then decides to end the run rather than take a tag. Seems like the AI should decide to take the tag or else not run that server, since it is a cost known in advance.

Thanks for your work on this, as a new player it is a great resource!

[chiriboga-log-2022-01-16T23_31_56.337Z.txt](https://github.com/bobtheuberfish/chiriboga/files/7878185/chiriboga-log-2022-01-16T23_31_56.337Z.txt)

**Comment by Timothy-Barron** [comment]
I encountered something similar with the AI running a rezzed whitespace, but not fully breaking it so the second sub ended the run.  It did this multiple times, burning its money in the process.

**Comment by bobtheuberfish** [comment]
Thank you both for your reports. Unfortunately I haven't been able to get this to happen for me. I can see from the logs that the bug definitely did happen - the AI plans the run and then ignores the plan. When I tested it just now with the same icebreakers, ice and server, the AI came up with the same plan as yours but then followed it perfectly.
So I will need more reports of this bug (ideally with logs and screenshots) to try and find out what I'm missing in my copy of the situation.
I can't spot anything in the game logic that would cause it so although that's still the most likely option it would be good to check external causes just in case. Can I ask what operating system and browser you're running? Also when was the first time you tried Chiriboga? (This was a more common problem in an older version of the game and your computer may be using a cached copy of the old file).

**Comment by beorik** [comment]
Interesting! I am using Chrome on Windows 10. I first tried Chiriboga within the last week, as far as I can recall? I suppose it is possible I tried it briefly in the past and forgot, I have been interested in Netrunner for awhile now.

**Comment by bobtheuberfish** [comment]
Hmm I guess we'll just have to wait and see if the issue comes up again.
I've made some changes to the game site so that it should use the most up-to-date script files from now on.

**Comment by bobtheuberfish** [comment]
This is improved but still happening. Will re-investigate.
