### ISSUE TITLE
Can't break subroutines after you un-highlight the ice

### ISSUE THREAD

**Issue by hbarsquared** [bobtheuberfish/chiriboga#43]
I just ran into a bug where I broke one subroutine on Whitespace, then forgot if Unity cost 1 or 2 to break subs. I clicked off of the ice which reverted it back to horizontal. I could not then continue to click on subroutines to break them - whenever I mouseover'd the ice it went vertical, but when I moved my cursor up to the subs it goes back horizontal. I was able to continue by allowing the unbroken sub to fire.

Firefox 96.0.1 (64-bit)

**Comment by bobtheuberfish** [comment]
Thank you for this report. Unfortunately I couldn't recreate your bug - with the subroutine choices up, no matter where I clicked I was not able to revert the card back to horizontal.
Had you already clicked the first subroutine and broken it, or do you mean that you had just clicked Unity and the subroutine choices had come up? If you have already broken the first subroutine then you don't click the second subroutine or anything on the ice, you just need to click Unity.
The "Resolve unbroken subroutines" button is not visible when you're choosing subroutines to break, It sounds like Unity should've been clickable at this time. If it wasn't, that would be a bug, but I can't get this to happen during testing.
If you can get this to happen again please take a screenshot and describe how you were able to replicate it.
