### ISSUE TITLE
Corp AI needs to be more tactical about which ice it rezzes

### ISSUE THREAD

**Issue by bobtheuberfish** [bobtheuberfish/chiriboga#44]
As reported by Saracenar on reddit:
"I was just playing a game and running on a server which turned out to have an agenda in it. The server was protected by two ICE, and I had a decoder and a killer in play, but the AI chose to rez a Whitespace instead of a Palisade. I assume this is because the Whitespace was the outermost ICE and the AI had enough credits at the time. Once I moved to the unrezzed Palisade it no longer had enough credits to rez it.
The Send a Message was also only advanced once. Generally the best play would to be install-advance-advance a 5/3 agenda."

**Comment by alexzhaohong** [comment]
Scenario: I, Runner, stole a _Send a Message_ from HQ. AI Corp, at 3c, decides between 3 unrezzed ICE to rez. AI decides to rez a _Ping_ on remote server 2 (_Snare!_ in the root of the server).

Why I think this is not the right tactic: _Ping_'s main value comes from its "On rez" effect. Also, Corp had enough credits to pay for _Ping_. One of the other ICE on R&D or HQ should have been rezzed for free instead.

Suggestion: For _Send a Message_, AI should not consider _Ping_ as an ICE to rez for free if it can pay for it normally. 

[chiriboga-log-2023-04-04T08_26_01.899Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11146368/chiriboga-log-2023-04-04T08_26_01.899Z.txt)
