### ISSUE TITLE
Zooming in on opponent cards causes confusion on 6 vs 9 counter

### ISSUE THREAD

**Issue by jorisbontje** [bobtheuberfish/chiriboga#48]
https://youtu.be/foNqCUuErwY?t=1981

**Comment by bobtheuberfish** [comment]
Thank you for reporting this! I had this written down from watching that very helpful stream. Looks like its a bug where the counter sometimes rotating with the card.
This is a low priority bug (the line underneath the number is my workaround for now) but it is certainly on my list.
