### ISSUE TITLE
Runner gets credits from Offworld Office on steal

### ISSUE THREAD

**Issue by chmontgomery** [bobtheuberfish/chiriboga#51]
Only corp should receive credits when scored. You can't tell from the log, but the runner got offworld office credits when stolen
[chiriboga-log-2022-01-23T13_06_18.238Z.txt](https://github.com/bobtheuberfish/chiriboga/files/7920565/chiriboga-log-2022-01-23T13_06_18.238Z.txt)

**Comment by chmontgomery** [comment]
just tested again. seems something else happened, but unsure what. suggestion: you could start logging credits of each player on start of turn for more helpful debugging.

**Comment by bobtheuberfish** [comment]
Thank you for your report and suggestion. Credits in the log is a good idea, I'll create a new issue about log improvement.

**Comment by chmontgomery** [comment]
also thanks for the work on this project. I've really enjoyed it!
