### ISSUE TITLE
Runner AI didn't follow plan

### ISSUE THREAD

**Issue by genbod** [bobtheuberfish/chiriboga#53]
I think this might be related to the previous bug of the runner AI not following through on its plan.  I am a new player and have been getting my butt kicked by the runner AI.  I finally won, but the runner AI didn't finish running my remote server which I thought for sure would cause me to lose the game.  This might be a little worse than the previous bug, because it could have easily broken the subroutine instead of letting it fire and it had several options besides not just following through and using all the virus counters.

[chiriboga-log-2022-01-23T22_13_19.812Z.txt](https://github.com/bobtheuberfish/chiriboga/files/7921610/chiriboga-log-2022-01-23T22_13_19.812Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report. This is a fairly high priority bug, I'll get to it relatively soon.
