### ISSUE TITLE
Bug: Public Trail, Predictive Planogram, Draw, Install

### ISSUE THREAD

**Issue by bb5wt6** [bobtheuberfish/chiriboga#65]
![nr_bug1](https://user-images.githubusercontent.com/99504228/153649836-4dbc6252-af2a-4aef-973f-652250cf6929.png)
[chiriboga-log-2022-02-11T18 24 17.011Z.txt](https://github.com/bobtheuberfish/chiriboga/files/8050897/chiriboga-log-2022-02-11T18.24.17.011Z.txt)

Screenshot and log file do not coincide !?!? Check side bar on the screenshot. I got confused, because I had a tag in the first turn, but did not understand why. Only read the log after the game.

I believe the Corp turn 1 was: Public Trail, Predictive Planogram, Install in remote server 1 

Public Trail didn't show up in the side bar and in the log file. Instead a draw action showed up.

**Comment by bobtheuberfish** [comment]
Thank you for this report. I believe you are correct. I'm glad you gave such a detailed report with screenshot and log because it's not obvious what has happened.
I will investigate.

**Comment by bobtheuberfish** [comment]
Fixed by pull request #68
