### ISSUE TITLE
NBN games consistently assign tags without appropriate action

### ISSUE THREAD

**Issue by YorickElRojo** [bobtheuberfish/chiriboga#66]
[chiriboga-log-2022-02-13T03_23_19.110Z.txt](https://github.com/bobtheuberfish/chiriboga/files/8054900/chiriboga-log-2022-02-13T03_23_19.110Z.txt)

It has happened multiple times, at the beginning of the game and when the corp plays Predictive Planogram (the log shows it getting the credits and the cards but there was no tag before that) or Retribution (the corp trashes a card but a tag was not given previously to the runner). I have not experienced this issue with other games against other corps playing this same operation.

**Comment by bobtheuberfish** [comment]
Thank you for this report. A similar issue was reported yesterday, so I believe this will be fixed this week. Thank you for providing the log.

**Comment by bobtheuberfish** [comment]
Fixed by pull request #68
