### ISSUE TITLE
'Longevity Serum' doesn't allow corp to trash cards from HQ.

### ISSUE THREAD

**Issue by RobDavenport** [bobtheuberfish/chiriboga#73]
The Jinteki faction agenda card Longevity Serum has the following text:

_When you score this agenda, trash any number of cards from HQ. Shuffle up to 3 cards from Archives into R&D._

_Limit 1 per deck._

The first effect of "trash any number of cards from HQ" doesn't seem to work. When scoring it, the choice of selecting cards from HQ does appear, but clicking them does nothing (it just lets you drag the cards, but you can't drag them to trash or anything). After clicking the continue button, the corp is correctly prompted to shuffle cards from Archives into R&D.

**Comment by bobtheuberfish** [comment]
Thank you for this report. This should be fixed now (drag cards to Archives to trash them).
