### ISSUE TITLE
Interface not clear that subroutines are clickable on ice

### ISSUE THREAD

**Issue by JohnnyQuazar** [bobtheuberfish/chiriboga#77]
My first game was going so well! The corp knew I was gonna win before it all locked up. I had to quit the browser window.

![Chiriboga_—_Mozilla_Firefox_2022-05-19_15-05-47](https://user-images.githubusercontent.com/7278265/169600651-85493064-f52c-4310-9db8-77fb6dc8bbe9.jpg)

I thought to check the console but it looked normal

![Chiriboga_—_Mozilla_Firefox_2022-05-19_15-10-15](https://user-images.githubusercontent.com/7278265/169600696-cb54547e-a4fa-4277-b324-084bff0bd560.png)

if this happened again what can I do to help? big fun keep going!!

**Comment by bobtheuberfish** [comment]
Thanks for the report!
The game is waiting for you to choose which subroutine to break.
You need to click one of the subroutines on the piece of ice you're encountering.
Please let me know if you have any ideas to make it clearer that the subroutines are clickable.

**Comment by JohnnyQuazar** [comment]
thanks :) I'm pretty sure my clicking did nothing but will check more carefully next time I play
