### ISSUE TITLE
How can I host my own Chiriboga?

### ISSUE THREAD

**Issue by 1to** [bobtheuberfish/chiriboga#79]
First and foremost, thank you for Chiriboga!

Now it's not really an issue with the game itself, but I want to try some stuff and maybe even be able to play even without internet connection. Tried downloading and running it myself, but it looks like the resources are missing, so I can't even load a game. What can I do?

**Comment by bobtheuberfish** [comment]
Thank you for this report. There are instructions to do this but they were out of date. I have now updated the links.
https://github.com/bobtheuberfish/chiriboga/wiki/Running-locally

**Comment by 1to** [comment]
> Thank you for this report. There are instructions to do this but they were out of date. I have now updated the links. https://github.com/bobtheuberfish/chiriboga/wiki/Running-locally

Bob, first and foremost thank you for all this work, this is really a godsend to get more people playing Netrunner :) second, I'm wondering if you're willing to work further on the app and revise some parts of it. I'm an illustrator (vector and painting) and an experienced designer who's entering the UX/UI field, and I have drawn some made some wireframes and made some tests in my own Chiriboga.

However, I'm trying to find solutions that use less resources, or just as much as you're using at the moment, and I'm trying to be mindful of mobile. Basically I'm looking for solutions that will hopefully simplify your work and make the app (much) more visually appealing and easier to understand and use.

If you're interested, find me at Telegram as @killthepast or at taito@disroot.org :) it would be amazing to get more people into this game. Feel free to tell me you're not interested in working with someone else or doing more work though, I'm thankful enough for being able to test stuff on it on my own.
