### ISSUE TITLE
Public trail gives a tag even if runner pays 8 (playing as runner)

### ISSUE THREAD

**Issue by BilbyHouse** [bobtheuberfish/chiriboga#80]
[chiriboga-log-2022-06-08T20 51 07.456Z.txt](https://github.com/bobtheuberfish/chiriboga/files/8864970/chiriboga-log-2022-06-08T20.51.07.456Z.txt)

**Comment by bobtheuberfish** [comment]
Thank you for this report and especially for including the log.
According to the log, Public Trail worked correctly. You received 1 tag during your turn (from encountering Funhouse) and then at the end of the Corp turn (after they played Public Trail) you still have just 1 tag.
I also (just now) tested myself playing as Runner, and when I paid the 8 credits I did not receive the tag.
