### ISSUE TITLE
Can't add Botulus when making a Zahya deck

### ISSUE THREAD

**Issue by R41B** [bobtheuberfish/chiriboga#81]
I really enjoy your AI netrunner platform! But when trying to create a Zahya deck in the "runner deck builder" part, I can't add Botulus. Even if I copy paste it from a Loup deck in another another tab, it doesn't work..
<img width="480" alt="Screenshot 2022-06-25 at 14 32 51" src="https://user-images.githubusercontent.com/108181770/175773674-7a88fe3d-0010-4b1d-b49a-da048e2e680e.png">

**Comment by bobtheuberfish** [comment]
Thank you for this report. I think I have fixed it, please refresh the deckbuilder page and try again.

**Comment by R41B** [comment]
Yes! it works now. Thank you so much!
