### ISSUE TITLE
Atman power counters don't require credits.

### ISSUE THREAD

**Issue by Kwaice** [bobtheuberfish/chiriboga#82]
Atman says : "When you install this program, you may pay Xcredit to place X power counters on it."

But it doesn't require any credit to place the power counters on it.

![image](https://user-images.githubusercontent.com/25953788/176190042-983eef12-2824-47a8-8f9b-298c47dbf354.png)

**Comment by bobtheuberfish** [comment]
Oh you're right! I've totally missed that line from the implementation. Easy fix, will test and upload a fix for this along with Corporate Troubleshooter (in a few days hopefully). Thank you!
