### ISSUE TITLE
Earthrise Hotel triggered in discard

### ISSUE THREAD

**Issue by Kwaice** [bobtheuberfish/chiriboga#83]
Aesop Pawn Shop and EH both installed at the beginning of the turn.

Trigger Pawn Shop first and trash EH.

EH still triggered from discard and drawed me 2 cards : 

![image](https://user-images.githubusercontent.com/25953788/176191214-562316bc-7572-4370-9b72-fd8285a7f3ba.png)

![image](https://user-images.githubusercontent.com/25953788/176191078-af94ec7d-e344-4112-876b-e0bb489c61b5.png)

**Comment by bobtheuberfish** [comment]
Thank you for this report. I think this issue may also affect other cards (e.g. Security Testing). I should be able to get to this within the next week or so.
