### ISSUE TITLE
Cleaver vs Bran 1.0 interaction

### ISSUE THREAD

**Issue by DeadEyeJim** [bobtheuberfish/chiriboga#86]
Hi there. Love this and wish I had had this years ago. One thing though, it seems in a couple games I’ve played now Cleaver is paying for each barrier subroutine, not one for up to two per the card. I noticed this when bypassing Bran 1.0, where Cleaver pays 3 rather than two. It happens fast so I could be mistaken. Also playing on iOS if that matters. I tried to attach it but it imported the whole file as text below. Thanks again.

Game begins
PixiJS 4.7.0 - WebGL - http://www.pixijs.com/
[The Catalyst,2 Cleaver,2 Tread Lightly,1 Docklands Pass,1 Pennyshaver,2 Carmen,1 Red Team,2 Creative Commission,2 VRcation,2 Unity,2 Telework Contract,3 Jailbreak,2 Overclock,3 Sure Gamble,2 Mayfly,2 Smartware Distributor,1 Verbal Plasticity]
[The Syndicate,2 Nico Campaign,2 Brân 1.0,2 Seamless Launch,1 Manegarm Skunkworks,2 Urtica Cipher,2 Diviner,2 Karunā,2 Government Subsidy,3 Offworld Office,2 Send a Message,2 Superconducting Hub,2 Regolith Mining License,3 Palisade,2 Tithe,2 Whitespace,3 Hedge Fund]
Decks shuffled
Each player has taken five credits and drawn five cards
AI: This hand will do
Corp chose to keep
Runner chose to keep
SPOILER: At start of Corp turn:
SPOILER: Corp has 5 credit(s) and 5 card(s) in hand: [Seamless Launch,Diviner,Whitespace,Superconducting Hub,Urtica Cipher]
SPOILER: Runner has 5 credit(s), 0 tag(s) and 5 card(s) in hand: [Sure Gamble,Smartware Distributor,Red Team,Mayfly,Creative Commission]
Corp drew a card
AI: Server protection scores: {HQ:-0.5,RnD:0,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: a relevant preference has been set
Corp spent one click
Corp installed ice protecting HQ
AI: Server protection scores: {HQ:3,RnD:0,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: a relevant preference has been set
Corp spent one click
Corp installed ice protecting R&D
AI: Server protection scores: {HQ:2,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Maybe could draw an economy card?
AI: But no I don't want to draw right now
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 6 credit(s) and 4 card(s) in hand: [Superconducting Hub,Send a Message,Seamless Launch,Urtica Cipher]
SPOILER: Runner has 5 credit(s), 0 tag(s) and 5 card(s) in hand: [Sure Gamble,Smartware Distributor,Red Team,Mayfly,Creative Commission]
Runner spent one click
Runner spent 5 credits
Played Sure Gamble
Runner gained 9 credits
Runner spent one click
Runner installed Smartware Distributor
Runner spent one click
Runner spent 5 credits
Runner installed Red Team
12 credits loaded onto Red Team
Runner spent one click
Runner spent one credit
Played Creative Commission
Runner gained 5 credits
Runner lost no clicks
SPOILER: At start of Corp turn:
SPOILER: Corp has 6 credit(s) and 4 card(s) in hand: [Superconducting Hub,Send a Message,Seamless Launch,Urtica Cipher]
SPOILER: Runner has 8 credit(s), 0 tag(s) and 1 card(s) in hand: [Mayfly]
Corp drew a card
AI: Server protection scores: {HQ:3,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Not sure what to do
AI: Hedge Fund might be good economy play?
Corp spent one click
Corp spent 5 credits
Played Hedge Fund
Corp gained 9 credits
AI: Server protection scores: {HQ:2,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Maybe could draw an economy card?
Corp spent one click
Corp drew a card
AI: Server protection scores: {HQ:3,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 11 credit(s) and 5 card(s) in hand: [Send a Message,Palisade,Urtica Cipher,Seamless Launch,Superconducting Hub]
SPOILER: Runner has 8 credit(s), 0 tag(s) and 1 card(s) in hand: [Mayfly]
Runner spent one click
Runner spent one credit
Runner installed Mayfly
Runner spent one click
Runner drew a card
Using Red Team:
Runner spent one click
Run initiated attacking HQ
Approaching outermost piece of ice protecting HQ
AI: I will rez the approached ice
Corp spent 2 credits
Corp rezzed Diviner
Encountering Diviner
Using Mayfly:
Runner spent one credit
Mayfly gets +1 strength
Using Mayfly:
Runner spent one credit
Mayfly gets +1 strength
Using Mayfly:
Runner spent one credit
Subroutine Do 1 net damage. If you trash a card with a printed play or install cost that is an odd number, end the run. broken
Approaching HQ
Run successful
3 credits taken from Red Team
Superconducting Hub accessed
Superconducting Hub stolen
Mayfly trashed
Using Smartware Distributor:
Runner spent one click
3 credits placed on Smartware Distributor
SPOILER: At start of Corp turn:
SPOILER: Corp has 9 credit(s) and 4 card(s) in hand: [Seamless Launch,Send a Message,Palisade,Urtica Cipher]
SPOILER: Runner has 7 credit(s), 0 tag(s) and 1 card(s) in hand: [Tread Lightly]
Corp drew a card
AI: Server protection scores: {HQ:-0.5,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: a relevant preference has been set
AI: phase is trash before install
AI: not helpful to trash anything right now
Corp spent one click
Corp spent one credit
Corp installed ice protecting HQ
AI: Server protection scores: {HQ:3.25,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Maybe could draw an economy card?
Corp spent one click
Corp drew a card
AI: Server protection scores: {HQ:2.25,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 9 credit(s) and 5 card(s) in hand: [Seamless Launch,Send a Message,Urtica Cipher,Offworld Office,Offworld Office]
SPOILER: Runner has 7 credit(s), 0 tag(s) and 1 card(s) in hand: [Tread Lightly]
1 credit taken from Smartware Distributor
Runner spent one click
Runner drew a card
Runner spent one click
Runner drew a card
Runner spent one click
Runner spent 5 credits
Runner installed Carmen
Runner spent one click
Runner spent one credit
Played VRcation
Runner drew 4 cards
Runner lost no clicks
SPOILER: At start of Corp turn:
SPOILER: Corp has 9 credit(s) and 5 card(s) in hand: [Seamless Launch,Send a Message,Urtica Cipher,Offworld Office,Offworld Office]
SPOILER: Runner has 2 credit(s), 0 tag(s) and 5 card(s) in hand: [Tread Lightly,Docklands Pass,Telework Contract,Cleaver,Tread Lightly]
Corp drew a card
AI: Server protection scores: {HQ:3.25,RnD:4.5,null:1,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: a relevant preference has been set
Corp spent one click
Corp installed ice protecting a remote server
AI: Server protection scores: {HQ:2.25,RnD:4.5,Remote 0:0.75,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:2.25,RnD:4.5,Remote 0:0.75,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 11 credit(s) and 5 card(s) in hand: [Send a Message,Offworld Office,Urtica Cipher,Seamless Launch,Offworld Office]
SPOILER: Runner has 2 credit(s), 0 tag(s) and 5 card(s) in hand: [Tread Lightly,Docklands Pass,Telework Contract,Cleaver,Tread Lightly]
1 credit taken from Smartware Distributor
Runner spent one click
Runner spent 3 credits
Runner installed Cleaver
Runner spent one click
Runner drew a card
Runner spent one click
Runner gained one credit
Runner spent one click
Runner spent one credit
Played Tread Lightly
Run initiated attacking R&D
Approaching outermost piece of ice protecting R&D
AI: I will rez the approached ice
Corp spent 5 credits
Corp rezzed Whitespace
Encountering Whitespace
Firing The Runner loses 3[c]. on Whitespace:
Runner lost no credits
Firing If the Runner has 6[c] or less, end the run. on Whitespace:
Run ended
SPOILER: At start of Corp turn:
SPOILER: Corp has 6 credit(s) and 5 card(s) in hand: [Send a Message,Offworld Office,Urtica Cipher,Seamless Launch,Offworld Office]
SPOILER: Runner has 0 credit(s), 0 tag(s) and 4 card(s) in hand: [Docklands Pass,Telework Contract,Tread Lightly,Mayfly]
Corp drew a card
AI: Server protection scores: {HQ:0.9250000000000007,RnD:3,Remote 0:0.75,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: a relevant preference has been set
AI: phase is trash before install
AI: not helpful to trash anything right now
Corp spent one click
Corp spent one credit
Corp installed ice protecting a remote server
AI: Server protection scores: {HQ:-0.07499999999999929,RnD:3,Remote 0:-1.3499999999999999,archives:3}
AI: Nothing to advance
AI: Scoring windows: [6.324999999999999]
AI: a relevant preference has been set
Corp spent one click
Corp installed a card in root of a remote server
AI: Server protection scores: {HQ:-1.0749999999999993,RnD:3,Remote 0:-1.3499999999999999,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Maybe could draw an economy card?
AI: But no I don't want to draw right now
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 6 credit(s) and 4 card(s) in hand: [Seamless Launch,Offworld Office,Offworld Office,Send a Message]
SPOILER: Runner has 0 credit(s), 0 tag(s) and 4 card(s) in hand: [Docklands Pass,Telework Contract,Tread Lightly,Mayfly]
1 credit taken from Smartware Distributor
Runner spent one click
Runner spent one credit
Runner installed Telework Contract
9 credits loaded onto Telework Contract
Using Telework Contract:
Runner spent one click
3 credits taken from Telework Contract
Using Smartware Distributor:
Runner spent one click
3 credits placed on Smartware Distributor
Runner spent one click
Runner spent 2 credits
Runner installed Docklands Pass
SPOILER: At start of Corp turn:
SPOILER: Corp has 6 credit(s) and 4 card(s) in hand: [Seamless Launch,Offworld Office,Offworld Office,Send a Message]
SPOILER: Runner has 1 credit(s), 0 tag(s) and 2 card(s) in hand: [Tread Lightly,Mayfly]
Corp drew a card
AI: Server protection scores: {HQ:-3.0749999999999993,RnD:3,Remote 0:-2.3499999999999996,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: [7.625]
AI: a relevant preference has been set
[hidden card] trashed
Corp spent one click
Corp installed a card in root of a remote server
AI: Server protection scores: {HQ:-1.0749999999999993,RnD:3,Remote 0:-1.3499999999999999,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Maybe could draw an economy card?
Corp spent one click
Corp drew a card
AI: Server protection scores: {HQ:-1.0749999999999993,RnD:3,Remote 0:-2.3499999999999996,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Superconducting Hub,Offworld Office,Seamless Launch,Offworld Office,Send a Message]
SPOILER: Runner has 1 credit(s), 0 tag(s) and 2 card(s) in hand: [Tread Lightly,Mayfly]
1 credit taken from Smartware Distributor
Runner spent one click
Runner drew a card
Using Telework Contract:
Runner spent one click
3 credits taken from Telework Contract
Runner spent one click
Runner spent 3 credits
Runner installed Unity
Runner spent one click
Runner spent one credit
Played Tread Lightly
Run initiated attacking Remote 0
Approaching outermost piece of ice protecting Remote 0
AI: Rez this is better than Palisade in HQ
AI: I will rez the approached ice
Corp spent 6 credits
Corp rezzed Palisade
Encountering Palisade
Firing End the run. on Palisade:
Run ended
SPOILER: At start of Corp turn:
SPOILER: Corp has 1 credit(s) and 5 card(s) in hand: [Superconducting Hub,Offworld Office,Seamless Launch,Offworld Office,Send a Message]
SPOILER: Runner has 1 credit(s), 0 tag(s) and 1 card(s) in hand: [Mayfly]
Corp drew a card
AI: Server protection scores: {HQ:-3.95,RnD:1.5,Remote 0:-2.125,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:-3.95,RnD:1.5,Remote 0:-2.125,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:-1.625,RnD:1.5,Remote 0:-2.125,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: considering discard options...
Corp discarded [hidden card]
SPOILER: At start of Runner turn:
SPOILER: Corp has 4 credit(s) and 5 card(s) in hand: [Offworld Office,Seamless Launch,Superconducting Hub,Send a Message,Offworld Office]
SPOILER: Runner has 1 credit(s), 0 tag(s) and 1 card(s) in hand: [Mayfly]
1 credit taken from Smartware Distributor
Using Telework Contract:
Runner spent one click
3 credits taken from Telework Contract
Telework Contract trashed
Runner spent one click
Runner drew a card
Runner spent one click
Run initiated attacking Remote 0
Approaching outermost piece of ice protecting Remote 0
Encountering Palisade
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Cleaver:
Runner spent one credit
Subroutine End the run. broken
Approaching next piece of ice protecting Remote 0
AI: I will rez the approached ice
Corp spent one credit
Corp rezzed Tithe
Encountering Tithe
Using Carmen:
Runner spent one credit
Subroutine Do 1 net damage. broken
Firing Gain 1[c]. on Tithe:
Corp gained one credit
Approaching Remote 0
Run successful
Send a Message accessed
Send a Message stolen
You may rez 1 installed piece of ice, ignoring all costs triggered
AI: I know this one
Corp rezzed Palisade
Runner spent one click
Runner gained one credit
SPOILER: At start of Corp turn:
SPOILER: Corp has 4 credit(s) and 5 card(s) in hand: [Offworld Office,Seamless Launch,Superconducting Hub,Send a Message,Offworld Office]
SPOILER: Runner has 2 credit(s), 0 tag(s) and 2 card(s) in hand: [Mayfly,Unity]
Corp drew a card
AI: Server protection scores: {HQ:-4.4,RnD:1.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:-4.4,RnD:1.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:-4.4,RnD:1.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: considering discard options...
Corp discarded [hidden card]
SPOILER: At start of Runner turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Send a Message,Superconducting Hub,Offworld Office]
SPOILER: Runner has 2 credit(s), 0 tag(s) and 2 card(s) in hand: [Mayfly,Unity]
1 credit taken from Smartware Distributor
Using Red Team:
Runner spent one click
Run initiated attacking R&D
Approaching outermost piece of ice protecting R&D
Encountering Whitespace
Using Unity:
Runner spent one credit
Subroutine The Runner loses 3[c]. broken
Using Unity:
Runner spent one credit
Subroutine If the Runner has 6[c] or less, end the run. broken
Approaching R&D
Run successful
3 credits taken from Red Team
Regolith Mining License accessed
Runner spent 3 credits
Regolith Mining License trashed
Using Smartware Distributor:
Runner spent one click
3 credits placed on Smartware Distributor
Runner spent one click
Runner drew a card
Runner spent one click
Runner drew a card
SPOILER: At start of Corp turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Send a Message,Superconducting Hub,Offworld Office]
SPOILER: Runner has 1 credit(s), 0 tag(s) and 4 card(s) in hand: [Mayfly,Unity,Pennyshaver,Sure Gamble]
Corp drew a card
AI: Server protection scores: {HQ:-4.4,RnD:0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: a relevant preference has been set
AI: phase is trash before install
AI: not helpful to trash anything right now
Corp spent one click
Corp spent 2 credits
Corp installed ice protecting HQ
AI: Server protection scores: {HQ:-3.002512626584708,RnD:0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:-3.002512626584708,RnD:0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Not sure what to do
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Send a Message,Superconducting Hub,Offworld Office]
SPOILER: Runner has 1 credit(s), 0 tag(s) and 4 card(s) in hand: [Mayfly,Unity,Pennyshaver,Sure Gamble]
1 credit taken from Smartware Distributor
Using Red Team:
Runner spent one click
Run initiated attacking R&D
Approaching outermost piece of ice protecting R&D
Encountering Whitespace
Using Unity:
Runner spent one credit
Subroutine The Runner loses 3[c]. broken
Using Unity:
Runner spent one credit
Subroutine If the Runner has 6[c] or less, end the run. broken
Approaching R&D
Run successful
3 credits taken from Red Team
Brân 1.0 accessed
Runner spent one click
Runner drew a card
Runner spent one click
Runner installed Smartware Distributor
Using Smartware Distributor:
Runner spent one click
3 credits placed on Smartware Distributor
SPOILER: At start of Corp turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Send a Message,Superconducting Hub,Offworld Office]
SPOILER: Runner has 3 credit(s), 0 tag(s) and 4 card(s) in hand: [Mayfly,Unity,Pennyshaver,Sure Gamble]
Corp drew a card
AI: Server protection scores: {HQ:-2.002512626584708,RnD:0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance
AI: Scoring windows: []
AI: No obvious install options
AI: No obvious economy option
AI: Scoring windows: []
AI: Scoring windows: []
AI: Oh I know, I'll install something
AI: Scoring windows: []
AI: phase is trash before install
AI: not helpful to trash anything right now
Corp spent one click
Corp spent 3 credits
Corp installed ice protecting HQ
AI: Server protection scores: {HQ:-2.9468911086754463,RnD:0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:-2.9468911086754463,RnD:0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 6 credit(s) and 5 card(s) in hand: [Superconducting Hub,Offworld Office,Send a Message,Offworld Office,Offworld Office]
SPOILER: Runner has 3 credit(s), 0 tag(s) and 4 card(s) in hand: [Mayfly,Unity,Pennyshaver,Sure Gamble]
1 credit taken from Smartware Distributor
1 credit taken from Smartware Distributor
Runner spent one click
Runner spent 5 credits
Played Sure Gamble
Runner gained 9 credits
Runner spent one click
Runner spent 3 credits
Runner installed Pennyshaver
Using Red Team:
Runner spent one click
Run initiated attacking R&D
Approaching outermost piece of ice protecting R&D
Encountering Whitespace
Using Unity:
Runner spent one credit
Subroutine The Runner loses 3[c]. broken
Using Unity:
Runner spent one credit
Subroutine If the Runner has 6[c] or less, end the run. broken
Approaching R&D
Run successful
1 credit placed on Pennyshaver
3 credits taken from Red Team
Red Team trashed
Palisade accessed
Runner spent one click
Runner drew a card
SPOILER: At start of Corp turn:
SPOILER: Corp has 6 credit(s) and 5 card(s) in hand: [Superconducting Hub,Offworld Office,Send a Message,Offworld Office,Offworld Office]
SPOILER: Runner has 7 credit(s), 0 tag(s) and 3 card(s) in hand: [Mayfly,Unity,Cleaver]
Corp drew a card
AI: Server protection scores: {HQ:1.1830127018922205,RnD:-0.5,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: a relevant preference has been set
AI: phase is trash before install
AI: not helpful to trash anything right now
Corp spent one click
Corp spent one credit
Corp installed ice protecting R&D
AI: Server protection scores: {HQ:-2.9468911086754463,RnD:1.875,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
AI: Server protection scores: {HQ:0.18301270189222052,RnD:1.875,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: Nothing good to do...
Corp spent one click
Corp gained one credit
SPOILER: At start of Runner turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Offworld Office,Superconducting Hub,Send a Message]
SPOILER: Runner has 7 credit(s), 0 tag(s) and 3 card(s) in hand: [Mayfly,Unity,Cleaver]
1 credit taken from Smartware Distributor
1 credit taken from Smartware Distributor
Using Smartware Distributor:
Runner spent one click
3 credits placed on Smartware Distributor
Using Pennyshaver:
Runner spent one click
1 credit placed on Pennyshaver
2 credits taken from Pennyshaver
Runner spent one click
Runner drew a card
Runner spent one click
Runner spent one credit
Played Creative Commission
Runner gained 5 credits
Runner lost no clicks
SPOILER: At start of Corp turn:
SPOILER: Corp has 7 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Offworld Office,Superconducting Hub,Send a Message]
SPOILER: Runner has 15 credit(s), 0 tag(s) and 3 card(s) in hand: [Mayfly,Unity,Cleaver]
Corp drew a card
AI: Server protection scores: {HQ:1.1830127018922205,RnD:1.875,Remote 0:0.6000000000000001,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: a relevant preference has been set
Corp spent one click
Corp installed a card in root of a remote server
Corp spent 2 credits
Corp rezzed Regolith Mining License
15 credits loaded onto Regolith Mining License
AI: Server protection scores: {HQ:-2.9468911086754463,RnD:1.875,Remote 0:0.6000000000000001,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: a click ability could provide economy
Using Regolith Mining License:
Corp spent one click
3 credits taken from Regolith Mining License
AI: Server protection scores: {HQ:0.18301270189222052,RnD:1.875,Remote 0:0.6000000000000001,null:1,archives:3}
AI: Nothing to advance (can't afford it)
AI: Scoring windows: []
AI: No obvious install options
AI: I am feeling poor
AI: a click ability could provide economy
Using Regolith Mining License:
Corp spent one click
3 credits taken from Regolith Mining License
SPOILER: At start of Runner turn:
SPOILER: Corp has 11 credit(s) and 5 card(s) in hand: [Offworld Office,Offworld Office,Offworld Office,Send a Message,Superconducting Hub]
SPOILER: Runner has 15 credit(s), 0 tag(s) and 3 card(s) in hand: [Mayfly,Unity,Cleaver]
1 credit taken from Smartware Distributor
1 credit taken from Smartware Distributor
Runner spent one click
Run initiated attacking R&D
Approaching outermost piece of ice protecting R&D
AI: I will rez the approached ice
Corp spent 3 credits
Corp rezzed Palisade
Encountering Palisade
Using Cleaver:
Runner spent one credit
Subroutine End the run. broken
Approaching next piece of ice protecting R&D
Encountering Whitespace
Using Unity:
Runner spent one credit
Subroutine The Runner loses 3[c]. broken
Firing If the Runner has 6[c] or less, end the run. on Whitespace:
Approaching R&D
Run successful
1 credit placed on Pennyshaver
Government Subsidy accessed
Runner spent one click
Run initiated attacking HQ
Approaching outermost piece of ice protecting HQ
AI: I will rez the approached ice
Corp spent 6 credits
Corp rezzed Brân 1.0
Encountering Brân 1.0
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Brân 1.0:
Runner spent one click
Subroutine You may install 1 piece of ice from HQ or Archives directly inward from this ice, ignoring all costs. broken
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Brân 1.0:
Runner spent one click
Subroutine End the run. broken
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Cleaver:
Runner spent one credit
Subroutine End the run. broken
Approaching next piece of ice protecting HQ
AI: I will rez the approached ice
Corp spent 2 credits
Corp rezzed Whitespace
Encountering Whitespace
Using Unity:
Runner spent one credit
Subroutine The Runner loses 3[c]. broken
Firing If the Runner has 6[c] or less, end the run. on Whitespace:
Approaching next piece of ice protecting HQ
Encountering Palisade
Using Cleaver:
Runner spent one credit
Subroutine End the run. broken
Approaching next piece of ice protecting HQ
Encountering Diviner
Using Unity:
Runner spent one credit
Unity gets +3 strength
Using Unity:
Runner spent one credit
Subroutine Do 1 net damage. If you trash a card with a printed play or install cost that is an odd number, end the run. broken
Approaching HQ
Run successful
1 credit placed on Pennyshaver
Offworld Office accessed
Offworld Office stolen
Runner has reached 6 agenda points
Runner wins
Corp agenda points: 0
Runner agenda points: 6
R&D size: 13
Grip size: 3
Agendas were stolen from: [HQ,remote,HQ]

SPOILER: Contents of remote servers:
SPOILER: Remote 0: [Regolith Mining License]

RunnerTestField(30076, [30030,30020,30032,30021,30012,30012,30027,30030,30018,30020], [30029,30021,30015,30028,30027,30030,30028,30029,30034,30028], [30032,30026,30006], [30033,30033,30013,30014,30015,30006,30026], [30070,30069,30067], cardBackTexturesRunner,glowTextures,strengthTextures);
CorpTestField(30077, [30075,30045,30040,30040,30071], [30037,30039,30047,30047,30075,30064,30042,30073,30075,30037,30046,30045,30064], [30067,30070,30067,30069], [], [30074,30072], [30046,30072,30074,30039], [[30071,30073,30072]], [], cardBackTexturesCorp,glowTextures,strengthTextures);
runner.rig.resources[0].credits=2;
runner.rig.hardware[1].credits=2;
corp.archives.cards[0].faceUp=true;
corp.archives.cards[4].faceUp=true;
corp.RnD.ice[0].rezzed=true;
corp.RnD.ice[1].rezzed=true;
corp.HQ.ice[0].rezzed=true;
corp.HQ.ice[1].rezzed=true;
corp.HQ.ice[2].rezzed=true;
corp.HQ.ice[3].rezzed=true;
corp.remoteServers[0].root[0].rezzed=true;
corp.remoteServers[0].root[0].credits=9;
corp.remoteServers[0].root[0].AITurnsInstalled=1;
corp.remoteServers[0].ice[0].rezzed=true;
corp.remoteServers[0].ice[1].rezzed=true;
corp.remoteServers[0].AISuccessfulRuns=1;
corp.RnD.AISuccessfulRuns=4;
corp.HQ.AISuccessfulRuns=2;

Version reference: Sun May 29 2022 00:15:59 GMT-0400 (EDT)

**Comment by bobtheuberfish** [comment]
Thank you for this report, especially for the detail and the log. Glad to hear you're enjoying it!

I have tested Cleaver with Bran and for me it correctly breaks 2 subroutines for just 1 credit.

Cleaver should cost 8 credits total to break Bran 1.0, which is what I'm correctly seeing in my testing. 3x2c to get to sufficient strength, then 1c for the first two subroutines and 1c for the last.

I notice in your log that you alternated between clicking on Cleaver (to up strength) and clicking on Bran (to use its click-to-break ability). Make sure to check for the light blue dotted line showing that Cleaver can interface with Bran, otherwise clicking Bran will use Bran's break ability, not Cleaver's.

I'll leave this issue open for a while in case it happens again, in which case please post another log or comment here.

In case you are interested, here is my log when I use it:
Encountering Brân 1.0
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Cleaver:
Runner spent 2 credits
Cleaver gets +1 strength
Using Cleaver:
Runner spent one credit
Subroutine You may install 1 piece of ice from HQ or Archives directly inward from this ice, ignoring all costs. broken
Subroutine End the run. broken
Using Cleaver:
Runner spent one credit
Subroutine End the run. broken
