### ISSUE TITLE
Running Wins when CORP scores superconducting HUB

### ISSUE THREAD

**Issue by kevinxmaa** [bobtheuberfish/chiriboga#87]
[chiriboga-log-2022-07-15T19_55_39.117Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9123679/chiriboga-log-2022-07-15T19_55_39.117Z.txt)

Corp AI had drawn their last card from the deck, and scored Superconducting HUB. They should have won on that step, but instead had preceded to follow the text and draw two cards, which from the empty deck caused them to lose.

**Comment by bobtheuberfish** [comment]
Thank you for this report. This behaviour is correct as far as I can tell. According to the log, the Superconducting Hub was the 6th agenda point the Corp scores (7 points are required to win). The other agendas scored were Tomorrow's Headline (2 pts) and Send a Message (3 points).

Just to be sure, I just now tested the scenario in which this would have been the 7th point, and it worked correctly (the Corp wins and is not given a chance to draw cards).

**Comment by kevinxmaa** [comment]
My bad, I misunderstood! Apologies
