### ISSUE TITLE
Docklands Pass not working?

### ISSUE THREAD

**Issue by exiledanimals** [bobtheuberfish/chiriboga#88]
[chiriboga-log-2022-07-20T06_46_30.577Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9147213/chiriboga-log-2022-07-20T06_46_30.577Z.txt)

I think Docklands pass is not working properly for me. The two HQ cards are highlighted but when I click on one card I am only allowed to end the access.

**Comment by bobtheuberfish** [comment]
Thank you for this report. I'm pretty sure I know how I broke this, I'll fix it soon! Thanks also for testing the su2021 version - it sure needs testing :)
