### ISSUE TITLE
Did the AI’s logic cause it to lose?

### ISSUE THREAD

**Issue by DeadEyeJim** [bobtheuberfish/chiriboga#90]
Hi there. I am enjoying this still and I am providing feedback on the AI logic.

In this game (see file), the Corp (AI) had a pretty solid board, with multiple ice defending all its servers. The game was close, and whoever scored or stole the next agenda would win. 

The AI chose to create a new server, and installed an agenda there, behind ice it couldn’t afford to rez, and so I grabbed it easily, winning the game. I think the better option would be for the AI to have taken all the revenue from Regolith Mining License first and, after that was trashed, place the agenda on that server, behind five ice, perhaps even waiting a turn to do so.

I would be curious to know if the AI is making “choices” here, or if there is something in its programming that would cause it to create a server in this situation. For example, if it has a agenda and all other servers are occupied, it then tries to make a new server in order to install the agenda it has in hand.

[chiriboga-log-2022-08-01T01_42_55.767Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9230326/chiriboga-log-2022-08-01T01_42_55.767Z.txt)

**Comment by bobtheuberfish** [comment]
Thanks for this feedback! This is excellent feedback - every time someone identifies a common foolish behaviour I can improve the AI slightly.
The short answer is yes, the AI's logic caused it to lose. The version you're playing is the stable version, last updated May 29. I believe that I identified and fixed this in the dev version on 12 July (when I was testing Snare!). There is still work to be done, for example in the next version I hope to prevent the Corp AI from clogging a perfectly good scoring server (e.g. with a SanSan City Grid) with a random economy asset. So feel free to continue to report these!
If you're interested in playing the unstable dev version, to experience the latest AI behaviours, use https://chiriboga.sifnt.net.au/su2021/
If you'd like to deckbuild but want to limit the card pool to only System Gateway, use these links:
https://chiriboga.sifnt.net.au/su2021/decklauncher.php?sets=systemgateway&p=r&r=random
https://chiriboga.sifnt.net.au/su2021/decklauncher.php?sets=systemgateway&p=c&c=random

**Comment by bobtheuberfish** [comment]
I have made a lot of changes since August and hopefully the AI is a bit smarter now. I'm sure it will still make bad decisions, feel free to report them.
Thanks again for your feedback!
