### ISSUE TITLE
Mutual Favor

### ISSUE THREAD

**Issue by logoliv** [bobtheuberfish/chiriboga#92]
Hello,
Mutual Favor doesn't propose the option to install the icebreaker program we just searched in case of a successful run, only puts it in the grip.
[chiriboga-log-2022-08-14T10 28 51.200Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9333199/chiriboga-log-2022-08-14T10.28.51.200Z.txt)
Thanks in advance,
Olivier

**Comment by bobtheuberfish** [comment]
Hi Olivier,
Thank you for this report.
According to the log, you had insufficient credits to install Carmen. So you would not be given the option to install it.

**Comment by logoliv** [comment]
Hi Bob,

Thanks for your answer, I misunderstood the card text and thought that the install was free :) So if you made a successful run you just win a free clic, not as attractive...

By the way, congratulations for making this program : I'm a newbye and it's nice to be able to play versus an AI !
Is there a difference between the github version and the internet one ? The first is tagged "dev" and the other isn't.

Olivier

**Comment by bobtheuberfish** [comment]
Thanks!

The one you've been playing only contains cards from System Gateway. The "dev" version also contains cards from System Update 2021. It is a work-in-progress so there are bugs. If you wish to test the "dev" version, it can be found here: https://chiriboga.sifnt.net.au/su2021/
