### ISSUE TITLE
Retrieval Run not retrieving

### ISSUE THREAD

**Issue by comfect** [bobtheuberfish/chiriboga#93]
The AI correctly initiates a Retrieval Run run when it can and a breaker was trashed, but when it hits archives it accesses cards instead of actually retrieving, meaning it doesn't actually get the breaker back.

**Comment by bobtheuberfish** [comment]
Hi,
Thank you for this report. I have not been able to get the behaviour you described. In my testing the AI installs the breaker rather than breaching.
If this happens again please attach the log file (and a screenshot, if possible), so I can determine the specific circumstances that might be causing the AI to make an incorrect choice.

**Comment by comfect** [comment]
I have finally managed to recreate the situation and the problem, which I mis-stated. The problem isn't the run itself, it's that it gives me (the Corp, but also the actual player) the choice, rather than the AI (the runner) taking the choice. I'm not familiar with the code to get the log file, but here's a screenshot: I have to hit either "Breach" or the card itself, but that shouldn't be my choice. 

In previous iterations, I'd blindly hit Breach, not noticing the card was also highlighted, and assuming the AI would make the choice at that point--but of course instead it breached.
![Giving me the option not the AI](https://user-images.githubusercontent.com/111321460/185490279-c36e3d83-7e38-42dc-8973-2acdb1acb69f.png)

**Comment by comfect** [comment]
[chiriboga-log-2022-08-18T20_39_27.041Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9377481/chiriboga-log-2022-08-18T20_39_27.041Z.txt)
Update: here's the log, this time I managed to hit the card and it correctly took back its Cleaver.

**Comment by bobtheuberfish** [comment]
This extra information was very helpful, I now have this replicating. Good catch! I'll include a fix in my next patch (when I finish SanSan City Grid).
Thanks!

**Comment by comfect** [comment]
Glad I'm not the only one experiencing it now! And thanks for all the work you've done on this, it's an amazing tool.
