### ISSUE TITLE
Pointless Abagnale trash

### ISSUE THREAD

**Issue by comfect** [bobtheuberfish/chiriboga#95]
Sorry to bring up another issue, but the AI just ran a server, trashed Abagnale to bypass Wraparound (which was a code gate thanks to Kit) and then...jacked out. I didn't rez any new ice or respond in any way to the bypass, so it wasn't new information that led it to jack out. This feels like an error, since now it doesn't have a code gate breaker. Worse, it was a Jailbreak run so it also fizzled the jailbreak by jacking out.
[chiriboga-log-2022-08-18T22_38_25.204Z.txt](https://github.com/bobtheuberfish/chiriboga/files/9378073/chiriboga-log-2022-08-18T22_38_25.204Z.txt)
![Aftermath of trashed Abagnale](https://user-images.githubusercontent.com/111321460/185507626-23b3a0b7-d631-4c01-aa7c-d8a5deeb2ecb.png)
.

**Comment by bobtheuberfish** [comment]
Thank you for reporting this. And thank your for the log and screenshot.
According to the log, the AI was planning to continue the run all the way through. So this is a bug. I'll look into it.
