### ISSUE TITLE
Carnivore not triggering?

### ISSUE THREAD

**Issue by matpip** [bobtheuberfish/chiriboga#96]
Thanks for designing this, I'm a new player and know nothing about programming - I can't seem to trigger Carnivore (i.e. trash two cards to trash a card I'm accessing). Is this me or a bug? Cheers!

**Comment by cmur2** [comment]
I recently played an [Anarch deck with Carnivore](https://chiriboga.sifnt.net.au/engine.php?sets=systemgateway&r=N4IglgJgpgdgLmOBPEAuEBmADDgjCAGhAGMBDAJwgGc0BtbLAJgE4CGW2cOHtOteeWPk2GNRwjBKkNckmXK5j2SxcNYMs6nJr4YF-fXt0AWE2Y0BWYVZk28dnADZhzjabfD32gOzDfG-20ADmEggF0AXyA) on Chiriboga and could successfully trigger the ability. IIRC it worked for me like that: Chiriboga was showing me the card that I was accessing, then I clicked on Carnivore (was highlighted) which works even if the accessed card has no trash cost printed and then dragged two cards out of my hand to my discard pile.

**Comment by bobtheuberfish** [comment]
Hi matpip,

Thank you for this report. If it happens again can you please post the log and a screenshot? This will help me identify what caused the issue.

Thank you cmur2 for your reply also.

**Comment by matpip** [comment]
Apologies, this issue is due to me not understanding a Netrunner rule (accessing cards) rather than a problem with the program. Thanks again for writing it, it's such a help to a new player!
