### ISSUE TITLE
Hardware Acceleration Requirement

### ISSUE THREAD

**Issue by nopouire** [bobtheuberfish/chiriboga#97]
Noticed that cards will not render at all in Chromium browsers if Hardware Accel is turned off.
Might be helpful to put a warning on the splash page for those unaware 

Tested with Chromium: 104.0.5112.102

**Comment by bobtheuberfish** [comment]
Hi nopouire,

Thank you for this feedback, good idea. I should be able to do this fairly easily but I don't want to make it too conspicuous (for example I wouldn't make it a popup that players would need to close every time the game opens). Which page do you think it should go on and where would you position it? Especially given that it will not be relevant for most players. Also if you can suggest an exact wording that would be useful too.

**Comment by nopouire** [comment]
I would have suggested just throwing a pop-up if you detect if it's off, but apparently (yet expectedly) there's no reliable way to determine that in Chrome. Even less so on Linux distros as it's not even officially supported.
So barring just replacing the OpenGL or CSS that's requiring it (I'm guessing it's from the card movement animations) I think adding a simple:

> **Hardware Acceleration is required to use this site**

In the bottom banner on the front page, next to or justified with the "Source code [available on GitHub]" would be great.
