### ISSUE TITLE
Femme Fatale and Tollbooth

### ISSUE THREAD

**Issue by Kwaice** [bobtheuberfish/chiriboga#99]
Hi,

When the runner decides to use Femme Fatale to bypass Tollbooth, he still looses 3 credits when encountering the ice, before getting the choice to bypass it or not.

I believe the runner should have the choice to trigger the bypass before getting taxed.

**Comment by bobtheuberfish** [comment]
Thank you for this report. Yes that's a bug, Femme is supposed to trigger first because it's the Runner's turn. I will also need to check the AI to make sure it understands this correctly as well.

**Comment by bobtheuberfish** [comment]
This was apparently fixed during a November patch which corrected AI understanding of bad publicity credits. I have tested this particular issue and it behaves correctly now for both the human and AI player.
